### PR TITLE
added files necessary to set up a release pipeline

### PR DESCRIPTION
**Pull request by Zhongtang**
Copying from https://github.com/screwdriver-cd/sd-cmd

### CODE REVIEW

**Review by Filbird — APPROVED** [review]

**Comment by minzcmu** [comment]
build failed?

**Comment by Zhongtang** [comment]
We don't have anything in the root yet. It will be there in the next PR ;)

**Review by minzcmu — APPROVED** [review]
okay, your call!

**Comment by tkyi** [comment]
You'll also need to add these secrets to the pipeline: GIT_KEY, GITHUB_TOKEN

**Review by tkyi — APPROVED** [review]
Missing LICENSE and CONTRIBUTING but you can add them later
https://github.com/screwdriver-cd/sd-cmd/blob/master/LICENSE
https://github.com/screwdriver-cd/coverage-sonar/blob/master/CONTRIBUTING.md

**Pull request merged**
